# Generated by Django 5.1.3 on 2024-12-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory_management",
            "0002_warehouse_remove_order_product_remove_order_quantity_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
    ]
